#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v18
# autospec commit: f35655a
#
Name     : umockdev
Version  : 0.18.4
Release  : 5
URL      : https://github.com/martinpitt/umockdev/releases/download/0.18.4/umockdev-0.18.4.tar.xz
Source0  : https://github.com/martinpitt/umockdev/releases/download/0.18.4/umockdev-0.18.4.tar.xz
Summary  : Mock hardware devices
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: umockdev-bin = %{version}-%{release}
Requires: umockdev-data = %{version}-%{release}
Requires: umockdev-lib = %{version}-%{release}
Requires: umockdev-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : gobject-introspection-dev
BuildRequires : libgudev-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libpcap)
BuildRequires : pkgconfig(libudev)
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
With this program and libraries you can easily create mock udev objects.
This is useful for writing tests for software which talks to
hardware devices.

%package bin
Summary: bin components for the umockdev package.
Group: Binaries
Requires: umockdev-data = %{version}-%{release}
Requires: umockdev-license = %{version}-%{release}

%description bin
bin components for the umockdev package.


%package data
Summary: data components for the umockdev package.
Group: Data

%description data
data components for the umockdev package.


%package dev
Summary: dev components for the umockdev package.
Group: Development
Requires: umockdev-lib = %{version}-%{release}
Requires: umockdev-bin = %{version}-%{release}
Requires: umockdev-data = %{version}-%{release}
Provides: umockdev-devel = %{version}-%{release}
Requires: umockdev = %{version}-%{release}

%description dev
dev components for the umockdev package.


%package lib
Summary: lib components for the umockdev package.
Group: Libraries
Requires: umockdev-data = %{version}-%{release}
Requires: umockdev-license = %{version}-%{release}

%description lib
lib components for the umockdev package.


%package license
Summary: license components for the umockdev package.
Group: Default

%description license
license components for the umockdev package.


%prep
%setup -q -n umockdev-0.18.4
cd %{_builddir}/umockdev-0.18.4
pushd ..
cp -a umockdev-0.18.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725471463
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs
cd ../buildavx2;
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/umockdev
cp %{_builddir}/umockdev-%{version}/COPYING %{buildroot}/usr/share/package-licenses/umockdev/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/umockdev-record
/V3/usr/bin/umockdev-run
/usr/bin/umockdev-record
/usr/bin/umockdev-run
/usr/bin/umockdev-wrapper

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/UMockdev-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/umockdev-1.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/umockdev-1.0/umockdev.h
/usr/lib64/libumockdev-preload.so
/usr/lib64/libumockdev.so
/usr/lib64/pkgconfig/umockdev-1.0.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libumockdev-preload.so.0.0.0
/V3/usr/lib64/libumockdev.so.0.3.0
/usr/lib64/libumockdev-preload.so.0
/usr/lib64/libumockdev-preload.so.0.0.0
/usr/lib64/libumockdev.so.0
/usr/lib64/libumockdev.so.0.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/umockdev/01a6b4bf79aca9b556822601186afab86e8c4fbf
